### ISSUE TITLE
Captions not quite right

### ISSUE THREAD

**Issue by jaxxstorm** [chanko/frinkiac#6]
I'm using this in a lita plugin, and comparing it to the hubot plugin here: https://github.com/okize/hubot-frinkiac/blob/master/src/frinkiac.coffee

It seems that often, the captions just aren't quite right, either they go off the image or are too large. Examples:

https://frinkiac.com/meme/S04E17/428427.jpg?lines=people,%20stop!%20we%20can%27t%20GIVE%20UP%20OUR%20DENTAL%20PLAN.%0ALENNY,%20WITHOUT%20THAT%20DENTAL%20PLAN

https://frinkiac.com/meme/S06E01/1130446.jpg?lines=THAT%20SINISTER-LOOKING%20KID%0AIS%20COMING%20TO%20KILL%20ME.%0AHELP!%20HELP!%20AAH!%0AFlanders:%20%E2%99%AA%20MARY%20HAD%20A%20LITTLE%20LAMB%20%E2%99%AA

Whereas the hubot plugin seems to format the captions correctly:

https://frinkiac.com/meme/S13E11/790331.jpg?lines=So%20it%27s%2C%20uh%2C%0Astandardized%20testing%20time%0Aagain.%20%0AHave%20you%20ever%20noticed%0Ahow%20the%20dumb%20kids%0A

I can't really tell why, although I noticed the hubot plugin does some encoding: https://github.com/okize/hubot-frinkiac/blob/master/src/frinkiac.coffee#L32-L34

**Comment by chanko** [comment]
@jaxxstorm thanks for bringing this to my attention.

Care to take a look at my proposed solution #7?

**Comment by jaxxstorm** [comment]
Looks great! thanks for the speedy turnaround
